wget https://rest.uniprot.org/uniprotkb/A0A0D0GY75.fasta
wget https://rest.uniprot.org/uniprotkb/A0A0D0IHC8.fasta
wget https://rest.uniprot.org/uniprotkb/A0A0D0ILW3.fasta
wget https://rest.uniprot.org/uniprotkb/A0A0K9L2V5.fasta
wget https://rest.uniprot.org/uniprotkb/A0A0K9L7F1.fasta
wget https://rest.uniprot.org/uniprotkb/A0A0P9TTN1.fasta
wget https://rest.uniprot.org/uniprotkb/A0A0P9TTN1.fasta
wget https://rest.uniprot.org/uniprotkb/A0A0P9TTN1.fasta
wget https://rest.uniprot.org/uniprotkb/A0A0Y7LXL8.fasta
wget https://rest.uniprot.org/uniprotkb/A0A158SV53.fasta
wget https://rest.uniprot.org/uniprotkb/A0A222C6U9.fasta
wget https://rest.uniprot.org/uniprotkb/A0A2R3FW93.fasta
wget https://rest.uniprot.org/uniprotkb/A0A2R3G4I6.fasta
wget https://rest.uniprot.org/uniprotkb/A0A2S9R9L5.fasta
wget https://rest.uniprot.org/uniprotkb/A0A2S9RCT5.fasta
wget https://rest.uniprot.org/uniprotkb/A0A2S9RD24.fasta
wget https://rest.uniprot.org/uniprotkb/A0A2S9RNU9.fasta
wget https://rest.uniprot.org/uniprotkb/A0A2S9RNU9.fasta
wget https://rest.uniprot.org/uniprotkb/A0A2S9RP06.fasta
wget https://rest.uniprot.org/uniprotkb/A0A2S9RQI1.fasta
wget https://rest.uniprot.org/uniprotkb/A0A2S9RQN7.fasta
wget https://rest.uniprot.org/uniprotkb/A0A2S9RRX5.fasta
wget https://rest.uniprot.org/uniprotkb/A0A2S9RSE1.fasta
wget https://rest.uniprot.org/uniprotkb/A0A2S9RZ00.fasta
wget https://rest.uniprot.org/uniprotkb/A0A2S9S0I4.fasta
wget https://rest.uniprot.org/uniprotkb/A0A2S9S134.fasta
wget https://rest.uniprot.org/uniprotkb/A0A2S9S409.fasta
wget https://rest.uniprot.org/uniprotkb/A0A2S9S410.fasta
wget https://rest.uniprot.org/uniprotkb/A0A2S9S5W7.fasta
wget https://rest.uniprot.org/uniprotkb/A0A2S9S7P8.fasta
wget https://rest.uniprot.org/uniprotkb/A0A2S9SGF2.fasta
wget https://rest.uniprot.org/uniprotkb/A0A2S9SI61.fasta
wget https://rest.uniprot.org/uniprotkb/A0A2S9SI85.fasta
wget https://rest.uniprot.org/uniprotkb/A0A2S9SJG3.fasta
wget https://rest.uniprot.org/uniprotkb/A0A2U9DWP8.fasta
wget https://rest.uniprot.org/uniprotkb/A0A2U9DWS3.fasta
wget https://rest.uniprot.org/uniprotkb/A0A2U9DXJ1.fasta
wget https://rest.uniprot.org/uniprotkb/A0A2U9DXN8.fasta
wget https://rest.uniprot.org/uniprotkb/A0A2U9DYC4.fasta
wget https://rest.uniprot.org/uniprotkb/A0A2U9DYK0.fasta
wget https://rest.uniprot.org/uniprotkb/A0A2U9DZ88.fasta
wget https://rest.uniprot.org/uniprotkb/A0A2U9DZ96.fasta
wget https://rest.uniprot.org/uniprotkb/A0A2U9E068.fasta
wget https://rest.uniprot.org/uniprotkb/A0A2V0SB94.fasta
wget https://rest.uniprot.org/uniprotkb/A0A2X1PIK2.fasta
wget https://rest.uniprot.org/uniprotkb/A0A2X1PL31.fasta
wget https://rest.uniprot.org/uniprotkb/A0A2X1PP70.fasta
wget https://rest.uniprot.org/uniprotkb/A0A2X1PUN3.fasta
wget https://rest.uniprot.org/uniprotkb/A0A2X1PYT7.fasta
wget https://rest.uniprot.org/uniprotkb/A0A2X1RLR9.fasta
wget https://rest.uniprot.org/uniprotkb/A0A2X1RTI2.fasta
wget https://rest.uniprot.org/uniprotkb/A0A2X4D9L4.fasta
wget https://rest.uniprot.org/uniprotkb/A0A2X4D9N5.fasta
wget https://rest.uniprot.org/uniprotkb/A0A2X4DA12.fasta
wget https://rest.uniprot.org/uniprotkb/A0A2X4DAL0.fasta
wget https://rest.uniprot.org/uniprotkb/A0A2X4DCV5.fasta
wget https://rest.uniprot.org/uniprotkb/A0A2X4DDD9.fasta
wget https://rest.uniprot.org/uniprotkb/A0A2X4DEU9.fasta
wget https://rest.uniprot.org/uniprotkb/A0A2X4DPP8.fasta
wget https://rest.uniprot.org/uniprotkb/A0A2X4DRA5.fasta
wget https://rest.uniprot.org/uniprotkb/A0A2X4DRD7.fasta
wget https://rest.uniprot.org/uniprotkb/A0A2X4DRL8.fasta
wget https://rest.uniprot.org/uniprotkb/A0A2X4DVT9.fasta
wget https://rest.uniprot.org/uniprotkb/A0A2X4DWG8.fasta
wget https://rest.uniprot.org/uniprotkb/A0A2X4E0Q9.fasta
wget https://rest.uniprot.org/uniprotkb/A0A2X4G1R8.fasta
wget https://rest.uniprot.org/uniprotkb/A0A2X4G1Y2.fasta
wget https://rest.uniprot.org/uniprotkb/A0A2X4G2D4.fasta
wget https://rest.uniprot.org/uniprotkb/A0A2X4G516.fasta
wget https://rest.uniprot.org/uniprotkb/A0A2X4G6C0.fasta
wget https://rest.uniprot.org/uniprotkb/A0A2X4G6S0.fasta
wget https://rest.uniprot.org/uniprotkb/A0A6V7R1Z7.fasta
wget https://rest.uniprot.org/uniprotkb/A0A7H5FQY6.fasta
wget https://rest.uniprot.org/uniprotkb/A0A7L4YHB4.fasta
wget https://rest.uniprot.org/uniprotkb/A0A7U7FXP2.fasta
wget https://rest.uniprot.org/uniprotkb/A0A7U7FXP4.fasta
wget https://rest.uniprot.org/uniprotkb/A0A808U428.fasta
wget https://rest.uniprot.org/uniprotkb/A0A852PCC4.fasta
wget https://rest.uniprot.org/uniprotkb/A0A852PK68.fasta
wget https://rest.uniprot.org/uniprotkb/A0A852PK68.fasta
wget https://rest.uniprot.org/uniprotkb/A0A852PM37.fasta
wget https://rest.uniprot.org/uniprotkb/A0A852PN84.fasta
wget https://rest.uniprot.org/uniprotkb/A0A852PU31.fasta
wget https://rest.uniprot.org/uniprotkb/A0A852PU31.fasta
wget https://rest.uniprot.org/uniprotkb/A0A852PWB3.fasta
wget https://rest.uniprot.org/uniprotkb/A0A852PY20.fasta
wget https://rest.uniprot.org/uniprotkb/A0A854CW86.fasta
wget https://rest.uniprot.org/uniprotkb/A0A8E5JKA0.fasta
wget https://rest.uniprot.org/uniprotkb/A0A9W5B3J5.fasta
wget https://rest.uniprot.org/uniprotkb/A0A9W5B3T3.fasta
wget https://rest.uniprot.org/uniprotkb/A0A9W5F2B4.fasta
wget https://rest.uniprot.org/uniprotkb/A0AA43SCS8.fasta
wget https://rest.uniprot.org/uniprotkb/A0AA45M7A4.fasta
wget https://rest.uniprot.org/uniprotkb/A0AA45MD33.fasta
wget https://rest.uniprot.org/uniprotkb/A0AA45RM18.fasta
wget https://rest.uniprot.org/uniprotkb/A0AA49JHH4.fasta
wget https://rest.uniprot.org/uniprotkb/A0AA49JHH4.fasta
wget https://rest.uniprot.org/uniprotkb/A0QRY5.fasta
wget https://rest.uniprot.org/uniprotkb/A0QRY6.fasta
wget https://rest.uniprot.org/uniprotkb/A0QSK6.fasta
wget https://rest.uniprot.org/uniprotkb/A0R1C2.fasta
wget https://rest.uniprot.org/uniprotkb/A6YCE8.fasta
wget https://rest.uniprot.org/uniprotkb/A6YCE8.fasta
wget https://rest.uniprot.org/uniprotkb/A6YCE8.fasta
wget https://rest.uniprot.org/uniprotkb/C1J7I7.fasta
wget https://rest.uniprot.org/uniprotkb/C1J7I7.fasta
wget https://rest.uniprot.org/uniprotkb/C7BL85.fasta
wget https://rest.uniprot.org/uniprotkb/G9FZR6.fasta
wget https://rest.uniprot.org/uniprotkb/I1ZAV2.fasta
wget https://rest.uniprot.org/uniprotkb/M4PH35.fasta
wget https://rest.uniprot.org/uniprotkb/M4PH35.fasta
wget https://rest.uniprot.org/uniprotkb/N0BM78.fasta
wget https://rest.uniprot.org/uniprotkb/N0BM78.fasta
wget https://rest.uniprot.org/uniprotkb/P10640.fasta
wget https://rest.uniprot.org/uniprotkb/P10641.fasta
wget https://rest.uniprot.org/uniprotkb/P14181.fasta
wget https://rest.uniprot.org/uniprotkb/P14212.fasta
wget https://rest.uniprot.org/uniprotkb/P22235.fasta
wget https://rest.uniprot.org/uniprotkb/P22236.fasta
wget https://rest.uniprot.org/uniprotkb/P22930.fasta
wget https://rest.uniprot.org/uniprotkb/P26093.fasta
wget https://rest.uniprot.org/uniprotkb/P33397.fasta
wget https://rest.uniprot.org/uniprotkb/P35755.fasta
wget https://rest.uniprot.org/uniprotkb/P35757.fasta
wget https://rest.uniprot.org/uniprotkb/P38368.fasta
wget https://rest.uniprot.org/uniprotkb/P38368.fasta
wget https://rest.uniprot.org/uniprotkb/P42782.fasta
wget https://rest.uniprot.org/uniprotkb/P42782.fasta
wget https://rest.uniprot.org/uniprotkb/P45354.fasta
wget https://rest.uniprot.org/uniprotkb/P45354.fasta
wget https://rest.uniprot.org/uniprotkb/P45356.fasta
wget https://rest.uniprot.org/uniprotkb/P45356.fasta
wget https://rest.uniprot.org/uniprotkb/P45356.fasta
wget https://rest.uniprot.org/uniprotkb/P45357.fasta
wget https://rest.uniprot.org/uniprotkb/P45357.fasta
wget https://rest.uniprot.org/uniprotkb/P45387.fasta
wget https://rest.uniprot.org/uniprotkb/P45387.fasta
wget https://rest.uniprot.org/uniprotkb/P45994.fasta
wget https://rest.uniprot.org/uniprotkb/P45995.fasta
wget https://rest.uniprot.org/uniprotkb/P45996.fasta
wget https://rest.uniprot.org/uniprotkb/P46025.fasta
wget https://rest.uniprot.org/uniprotkb/P64602.fasta
wget https://rest.uniprot.org/uniprotkb/P71401.fasta
wget https://rest.uniprot.org/uniprotkb/P71401.fasta
wget https://rest.uniprot.org/uniprotkb/Q02047.fasta
wget https://rest.uniprot.org/uniprotkb/Q04IN8.fasta
wget https://rest.uniprot.org/uniprotkb/Q0ZAZ6.fasta
wget https://rest.uniprot.org/uniprotkb/Q0ZAZ6.fasta
wget https://rest.uniprot.org/uniprotkb/Q2ERF8.fasta
wget https://rest.uniprot.org/uniprotkb/Q2PBP7.fasta
wget https://rest.uniprot.org/uniprotkb/Q2PBP7.fasta
wget https://rest.uniprot.org/uniprotkb/Q2PBP7.fasta
wget https://rest.uniprot.org/uniprotkb/Q2VLI1.fasta
wget https://rest.uniprot.org/uniprotkb/Q3IZG2.fasta
wget https://rest.uniprot.org/uniprotkb/Q3YNQ7.fasta
wget https://rest.uniprot.org/uniprotkb/Q47330.fasta
wget https://rest.uniprot.org/uniprotkb/Q48029.fasta
wget https://rest.uniprot.org/uniprotkb/Q48030.fasta
wget https://rest.uniprot.org/uniprotkb/Q48032.fasta
wget https://rest.uniprot.org/uniprotkb/Q48033.fasta
wget https://rest.uniprot.org/uniprotkb/Q48037.fasta
wget https://rest.uniprot.org/uniprotkb/Q48152.fasta
wget https://rest.uniprot.org/uniprotkb/Q48152.fasta
wget https://rest.uniprot.org/uniprotkb/Q48152.fasta
wget https://rest.uniprot.org/uniprotkb/Q48154.fasta
wget https://rest.uniprot.org/uniprotkb/Q48230.fasta
wget https://rest.uniprot.org/uniprotkb/Q48IZ8.fasta
wget https://rest.uniprot.org/uniprotkb/Q48LT5.fasta
wget https://rest.uniprot.org/uniprotkb/Q4QL36.fasta
wget https://rest.uniprot.org/uniprotkb/Q4QMX3.fasta
wget https://rest.uniprot.org/uniprotkb/Q4QN94.fasta
wget https://rest.uniprot.org/uniprotkb/Q4QN95.fasta
wget https://rest.uniprot.org/uniprotkb/Q57394.fasta
wget https://rest.uniprot.org/uniprotkb/Q58LW9.fasta
wget https://rest.uniprot.org/uniprotkb/Q5D8D4.fasta
wget https://rest.uniprot.org/uniprotkb/Q5D8D5.fasta
wget https://rest.uniprot.org/uniprotkb/Q5D8D6.fasta
wget https://rest.uniprot.org/uniprotkb/Q5D8D7.fasta
wget https://rest.uniprot.org/uniprotkb/Q5D8D8.fasta
wget https://rest.uniprot.org/uniprotkb/Q5D8D9.fasta
wget https://rest.uniprot.org/uniprotkb/Q5D8E0.fasta
wget https://rest.uniprot.org/uniprotkb/Q5D8E1.fasta
wget https://rest.uniprot.org/uniprotkb/Q5D8E2.fasta
wget https://rest.uniprot.org/uniprotkb/Q5D8E3.fasta
wget https://rest.uniprot.org/uniprotkb/Q5SF32.fasta
wget https://rest.uniprot.org/uniprotkb/Q6H1A0.fasta
wget https://rest.uniprot.org/uniprotkb/Q6H1A0.fasta
wget https://rest.uniprot.org/uniprotkb/Q6H1A0.fasta
wget https://rest.uniprot.org/uniprotkb/Q7WRG5.fasta
wget https://rest.uniprot.org/uniprotkb/Q83T97.fasta
wget https://rest.uniprot.org/uniprotkb/Q83UA2.fasta
wget https://rest.uniprot.org/uniprotkb/Q83UD3.fasta
wget https://rest.uniprot.org/uniprotkb/Q83UD3.fasta
wget https://rest.uniprot.org/uniprotkb/Q83UM7.fasta
wget https://rest.uniprot.org/uniprotkb/Q83UM7.fasta
wget https://rest.uniprot.org/uniprotkb/Q83UM7.fasta
wget https://rest.uniprot.org/uniprotkb/Q83V78.fasta
wget https://rest.uniprot.org/uniprotkb/Q83V78.fasta
wget https://rest.uniprot.org/uniprotkb/Q8L2H7.fasta
wget https://rest.uniprot.org/uniprotkb/Q8RLZ3.fasta
wget https://rest.uniprot.org/uniprotkb/Q93N95.fasta
wget https://rest.uniprot.org/uniprotkb/Q99309.fasta
wget https://rest.uniprot.org/uniprotkb/Q99309.fasta
wget https://rest.uniprot.org/uniprotkb/Q9K392.fasta
wget https://rest.uniprot.org/uniprotkb/Q9KIV2.fasta
wget https://rest.uniprot.org/uniprotkb/Q9S657.fasta
wget https://rest.uniprot.org/uniprotkb/W8V0H6.fasta
